name: Prod - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-prod:
    runs-on: [self-hosted, windows]
    steps:
     # 0. Stopping prod
      - name: pm2 stopping prod
        shell: powershell
        run: pm2 stop LifePulse-prod
        
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        shell: powershell
        run: |
            cd backend
            npm ci

      # 5. Deploy (custom PowerShell script)
      - name: Deploy to production
        shell: powershell
        run: .\scripts\deploy.ps1 -env 'production' -appName 'LifePulse-prod'
